### PR TITLE
Fix natspec on morphoWithdraw

### PR DESCRIPTION
**Pull request by Jean-Grimal**
Fixes https://cantina.xyz/code/8409a0ce-6c21-4cc9-8ef2-bd77ce7425af/findings/637922bd-c38b-4ea0-bb51-a1420a47d088

### CODE REVIEW

**Review by MerlinEgalite — COMMENTED** [review]
I think there are some other issue on the bundler no?

**Comment by Jean-Grimal** [comment]
> I think there are some other issues on the bundlers no?

The issue also suggests to update the comments `@dev Initiator must have previously transferred their assets to the bundler.` because it's not true for native tokens (which can be sent within the call), but @Rubilmax and I don't think we should make the change

**Review by Rubilmax — APPROVED** [review]

**Comment by MerlinEgalite** [comment]
> but @Rubilmax and I don't think we should make the change

What's the reason?

**Comment by Rubilmax** [comment]
> What's the reason?

They are arguing in the case of ETH it doesn't require to be sent prior to the call, it can be sent as value of the CALL.. This is politics

**Review by MerlinEgalite — APPROVED** [review]

**Review by QGarchery — APPROVED** [review]

**Review by MathisGD — APPROVED** [review]

**Pull request merged**
