### PR TITLE
test: simplify chain setup

### PR DESCRIPTION
**Pull request by MathisGD**
Replaces #459

### CODE REVIEW

**Comment by adhusson** [comment]
With this PR, `forge test` without extra config will throw errors, which would be unexpected.

I liked the previous approach of forking is chain id is 31337. It meant that fork-only tests ran as well when I did `forge test`. What is unsafe about it?

An alternative would be to just skip all fork-only tests when tests are run on a local chain.

**Review by adhusson — COMMENTED** [review]
With this PR, the usual `forge test` during development will fail.

I like the current approach, it means that fork-only tests run as well when I run `forge test`. What is unsafe about it?

Alternatively they could just be skipped.

**Comment by MathisGD** [comment]
It seems safer to me because you explicitly say that you run tests on one chain (**and not on the other**)

**Comment by adhusson** [comment]
Afte reading [this](https://github.com/morpho-org/morpho-blue-bundlers/pull/459#pullrequestreview-2399319771) closing in favor of #459.

**Pull request closed without merging**
